#!/bin/bash
#
# To use this script, set the following environment variables:
#
#   godm_MYSQL_DSN - mysql connect DSN, like "godmtest/godmtest/godmtest"
#   godm_POSTGRES_DSN - postgres connect DSN, eg:
#        "username=godmtest password=godmtest dbname=godmtest ssl-mode=disable"
#   godm_SQLITE_DSN - sqlite connect DSN, which is a path to a sqlite file.
#   godm_FAIL_ON_SKIP - optional, will fail if any DBs are skipped (for CI, mostly)
#
# In addition to this, you can create an `environ` file in this directory which
# will be sourced and ignored by git.
#
# Additional arguments to test-all will be used after go-test, so to run
# the benchmark suite on all dbs you can do:
#   ./test-all -bench=. -benchmem
#

if [ -f "./environ" ]; then
    . ./environ
fi

function exit_on_error {
    if [ $1 != 0 ]; then
        exit $1
    fi
}

# set -e

if [ -n "$godm_MYSQL_DSN" ]; then
    export godm_TEST_DSN="$godm_MYSQL_DSN"
    export godm_TEST_DIALECT="mysql"
    echo "Testing MySQL"
    go test $@
    exit_on_error $?
else
    echo "Skipping MySQL, \$godm_MYSQL_DSN=$godm_MYSQL_DSN"
    if [ -n "$godm_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

if [ -n "$godm_POSTGRES_DSN" ]; then
    export godm_TEST_DSN="$godm_POSTGRES_DSN"
    export godm_TEST_DIALECT="postgres"
    echo "Testing PostgreSQL"
    go test $@
    exit_on_error $?
else
    echo "Skipping PostgreSQL, \$godm_POSTGRES_DSN=$godm_POSTGRES_DSN"
    if [ -n "$godm_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

if [ -n "$godm_SQLITE_DSN" ]; then
    export godm_TEST_DSN="$godm_SQLITE_DSN"
    export godm_TEST_DIALECT="sqlite"
    echo "Testing SQLite"
    go test $@
    exit_on_error $?
else
    echo "Skipping SQLite, \$godm_SQLITE_DSN=$godm_SQLITE_DSN"
    if [ -n "$godm_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

